language: perl
perl:
  - "5.8.8"
  - "5.8.9-thr"
  - "5.8"
  - "5.10"
  - "5.10.0-thr"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.20"
  - "dev"
matrix:
  include:
    - perl: 5.6
      env: AUTHOR_TESTING=0
    - perl: 5.8.1
      env: AUTHOR_TESTING=0
    - perl: 5.18
      env: COVERAGE=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
script:
  - perl Makefile.PL
  - make
  - prove -lv $(test-dirs)
branches:
  except:
    - /^wip\//
    - /^blocked/
sudo: false
notifications:
  email: false
  irc:
    channels:
      - "irc.perl.org#moo-smoke"
    template:
      - "%{branch}#%{build_number} by %{author}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
    skip_join: true
